console.log("Моя собственная оценка задания")
console.log("Верстка валидная,+10,есть header main footer,+2")
console.log("Нет элементов section h1 h2,-6")
console.log("Есть элемент nav,+2,но нет сипска ul li,кнопок button и элемента textarea,-6")
console.log("есть два инпута и 3 placeholder +4")
console.log("Верстка соответствует макету +48")
console.log("нет флексов или гридов -2 , при уменьшении масштаба страница по центру расположена а цвет фона не меняется добавлены иконки svg изображения jpg и favicon +10")
console.log("интерактивность css все выполнено +20")
console.log("Итого 86 баллов")